FROM ubuntu:24.04

ENV DOTFILES_REPO="https://github.com/TheLazyFerret/dots-and-templates.git"

USER root
WORKDIR /root

# Install basic packages
RUN apt-get update  && \
    apt-get upgrade -y && \
    apt-get install -y gcc g++ vim ssh curl git make cmake gdb

# Install rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs -o rustup.sh && \
    bash rustup.sh -y && \
    rm rustup.sh

# Configure dotfiles
RUN git clone $DOTFILES_REPO dotfiles && \
    cp dotfiles/vim/vimrc /root/.vimrc

# Miscellaneous
RUN mkdir -p .ssh/
